config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'

  get 'notifications/index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only: [:index, :show]

  resources :relationships, only: [:create, :destroy]

  resources :blogs do
    resources :comments
    post :confirm, on: :collection
  end
  
  resources :contacts, only: [:new, :create] do
    collection do
      post :confirm
    end
  end
  
  resources :poems, only: [:index, :show]
  
  resources :conversations do
    resources :messages
  end
  
  root 'top#index'
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  belongs_to :comment
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @notifications = Notification.where(user_id: current_user.id).where(read: false).order(created_at: :desc)
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def posted_time(time)
    time > Date.today ? "#{time_ago_in_words(time)}" : time.strftime('%m月%d日')
  end
end

app/views/notifications/index.html.erb
<div class="container">
  <div class="wrapper col-md-4 col-md-offset-4 col-sm-10">
    <h2>お知らせ</h2>
  <hr>
  <% @notifications.each do |notification| %>

    <div class="row">
      <span><strong>未読</strong></span>
      <p>
        <%= notification.comment.user.try(:name) %>さんが
        あなたのブログ（<%= link_to "#{notification.comment.blog.title}", blog_path(notification.comment.blog, notification_id: notification.id) %>）にコメントしました。
      </p>
      <p><%= posted_time(notification.created_at) %></p>
    </div>
  <% end %>

 </div>
</div>